{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teamclaw.configSecretName" . }}
  labels:
    {{- include "teamclaw.labels" . | nindent 4 }}
type: Opaque
stringData:
  openclaw.json: |
{{ include "teamclaw.openclawConfig" . | indent 4 }}
{{- end }}
