{{- if .Values.workerServiceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "teamclaw.workerServiceAccountName" . }}
  labels:
    {{- include "teamclaw.labels" . | nindent 4 }}
  {{- with .Values.workerServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.workerServiceAccount.automount }}
{{- end }}
